name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # show current directory
  pwd:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: show current directory
      run: ls ${{ github.workspace }}

  # build docker image using dockerfile in github repo
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: build docker image
      run: docker build -t sehoon0519/docker-react-app -f Dockerfile.dev ./

    - name: test docker image
      run: docker run -e CI=true sehoon0519/docker-react-app npm run test -- --coverage

    run: echo "Success!"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: Push to S3
      uses: aws-actions/aws-elasticbeanstalk-publish-to-s3@v1
      with:
        app-name: docker-react-app
        bucket-name: docker-react-app-s3
        version-label: ${{ github.sha }}
    
    - name: Deploy to Elastic Beanstalk
      uses: aws-actions/aws-elasticbeanstalk-deploy-version@v1
      with:
        app-name: docker-react-app
        environment-name: docker-react-app-env
        version-label: ${{ github.sha }}

    
  



  

