name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # show current directory
  pwd:
    runs-on: ubuntu-latest
    steps:
    - name: show current directory
      run: ls -l

  # build docker image using github repo as context
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build docker image
      run: docker build -t github-actions-demo .
  

